/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AirportsRouteImport } from './routes/airports'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PassengersRouteImport } from './routes/passengers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AircraftIndexRouteImport } from './routes/aircraft.index'
import { Route as AircraftAircraftidRouteImport } from './routes/aircraft.$aircraftid'
import { Route as FlightsFlightidRouteImport } from './routes/flights.$flightid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsRoute = AirportsRouteImport.update({
  id: '/airports',
  path: '/airports',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengersRoute = PassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftIndexRoute = AircraftIndexRouteImport.update({
  id: '/aircraft/',
  path: '/aircraft/',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftAircraftidRoute = AircraftAircraftidRouteImport.update({
  id: '/aircraft/$aircraftid',
  path: '/aircraft/$aircraftid',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsFlightidRoute = FlightsFlightidRouteImport.update({
  id: '/$flightid',
  path: '/$flightid',
  getParentRoute: () => FlightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airports': typeof AirportsRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/crew': typeof CrewRoute
  '/flights': typeof FlightsRouteWithChildren
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/operations': typeof OperationsRoute
  '/passengers': typeof PassengersRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/aircraft/$aircraftid': typeof AircraftAircraftidRoute
  '/flights/$flightid': typeof FlightsFlightidRoute
  '/aircraft/': typeof AircraftIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airports': typeof AirportsRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/crew': typeof CrewRoute
  '/flights': typeof FlightsRouteWithChildren
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/operations': typeof OperationsRoute
  '/passengers': typeof PassengersRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/aircraft/$aircraftid': typeof AircraftAircraftidRoute
  '/flights/$flightid': typeof FlightsFlightidRoute
  '/aircraft': typeof AircraftIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airports': typeof AirportsRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/crew': typeof CrewRoute
  '/flights': typeof FlightsRouteWithChildren
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/operations': typeof OperationsRoute
  '/passengers': typeof PassengersRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/aircraft/$aircraftid': typeof AircraftAircraftidRoute
  '/flights/$flightid': typeof FlightsFlightidRoute
  '/aircraft/': typeof AircraftIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airports'
    | '/analytics'
    | '/bookings'
    | '/crew'
    | '/flights'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/operations'
    | '/passengers'
    | '/profile'
    | '/routes'
    | '/settings'
    | '/aircraft/$aircraftid'
    | '/flights/$flightid'
    | '/aircraft/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airports'
    | '/analytics'
    | '/bookings'
    | '/crew'
    | '/flights'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/operations'
    | '/passengers'
    | '/profile'
    | '/routes'
    | '/settings'
    | '/aircraft/$aircraftid'
    | '/flights/$flightid'
    | '/aircraft'
  id:
    | '__root__'
    | '/'
    | '/airports'
    | '/analytics'
    | '/bookings'
    | '/crew'
    | '/flights'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/operations'
    | '/passengers'
    | '/profile'
    | '/routes'
    | '/settings'
    | '/aircraft/$aircraftid'
    | '/flights/$flightid'
    | '/aircraft/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirportsRoute: typeof AirportsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookingsRoute: typeof BookingsRoute
  CrewRoute: typeof CrewRoute
  FlightsRoute: typeof FlightsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NotificationsRoute: typeof NotificationsRoute
  OperationsRoute: typeof OperationsRoute
  PassengersRoute: typeof PassengersRoute
  ProfileRoute: typeof ProfileRoute
  RoutesRoute: typeof RoutesRoute
  SettingsRoute: typeof SettingsRoute
  AircraftAircraftidRoute: typeof AircraftAircraftidRoute
  AircraftIndexRoute: typeof AircraftIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports': {
      id: '/airports'
      path: '/airports'
      fullPath: '/airports'
      preLoaderRoute: typeof AirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passengers': {
      id: '/passengers'
      path: '/passengers'
      fullPath: '/passengers'
      preLoaderRoute: typeof PassengersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft/': {
      id: '/aircraft/'
      path: '/aircraft'
      fullPath: '/aircraft/'
      preLoaderRoute: typeof AircraftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft/$aircraftid': {
      id: '/aircraft/$aircraftid'
      path: '/aircraft/$aircraftid'
      fullPath: '/aircraft/$aircraftid'
      preLoaderRoute: typeof AircraftAircraftidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/$flightid': {
      id: '/flights/$flightid'
      path: '/$flightid'
      fullPath: '/flights/$flightid'
      preLoaderRoute: typeof FlightsFlightidRouteImport
      parentRoute: typeof FlightsRoute
    }
  }
}

interface FlightsRouteChildren {
  FlightsFlightidRoute: typeof FlightsFlightidRoute
}

const FlightsRouteChildren: FlightsRouteChildren = {
  FlightsFlightidRoute: FlightsFlightidRoute,
}

const FlightsRouteWithChildren =
  FlightsRoute._addFileChildren(FlightsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirportsRoute: AirportsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookingsRoute: BookingsRoute,
  CrewRoute: CrewRoute,
  FlightsRoute: FlightsRouteWithChildren,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  NotificationsRoute: NotificationsRoute,
  OperationsRoute: OperationsRoute,
  PassengersRoute: PassengersRoute,
  ProfileRoute: ProfileRoute,
  RoutesRoute: RoutesRoute,
  SettingsRoute: SettingsRoute,
  AircraftAircraftidRoute: AircraftAircraftidRoute,
  AircraftIndexRoute: AircraftIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
